name: Publish packages to GHCR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  publish_docker_image:
    uses: keeleinstituut/tv-devops/.github/workflows/docker-build-publish.yaml@feature/#116
  publish_helm_image:
    needs: publish_docker_image
    uses: keeleinstituut/tv-devops/.github/workflows/helm-package-publish.yaml@feature/#116
